### PR TITLE
fix: vod page user-interface

### PR DESCRIPTION
**Pull request by Toxocious**
Attempts to resolves issue #32.

Minor fix for the VOD listings displayed in `/src/app/(components)/vods.tsx`, now ensuring that no VODs are missing/clipped from the page when displayed.

- Removes overflowing on the y-axis
- Improves vod item and vod container centering

As I only have one Twitch VOD, I duplicated the element *n* times to test responsiveness.

<details>
  <summary>Mobile & Desktop Screenshots</summary>
  
  localhost_3000_toxocious
  localhost_3000_toxocious (1)
  localhost_3000_toxocious (2)
  localhost_3000_toxocious (3)
</details>

### CODE REVIEW

**Comment by markflorkowski** [comment]
I would like to preserve y-overflow so that the footer remains visible.

also note for testing, you should be able to use another user's username (eg. `/theo` or `/theprimeagen`) for a view with additional vods

**Comment by Toxocious** [comment]
> I would like to preserve y-overflow so that the footer remains visible.
> 
> also note for testing, you should be able to use another user's username (eg. `/theo` or `/theprimeagen`) for a view with additional vods

Ah, gotcha. I'll fix that and reply once done, haha.

Appreciate the note btw, that's excellent.

**Comment by Toxocious** [comment]
Overflowing on the y-axis is now preserved.

<details>
  <summary>Mobile & Desktop Screenshots</summary>
  
  localhost_3000_theo
  localhost_3000_theo (1)
  localhost_3000_theo (2)
  localhost_3000_theo(Pixel 5)
  localhost_3000_theo(Pixel 5) (1)
  localhost_3000_theo(Pixel 5) (2)
</details>

**Comment by markflorkowski** [comment]
Got it working in the branch `mark/responsive-fix` -- I was missing an `my-auto`. I think I like your `max-w` approach better than a fixed `w-3/4` that I was using though

**Comment by Toxocious** [comment]
Yeah, I liked `max-w` over the alternatives, hah.

Excellent stuff though; glad to hear you got it working.

**Review by markflorkowski — APPROVED** [review]

**Pull request merged**
